In [1]:
2+2


4

In [14]:
import mlflow
import mlflow.pytorch
import torch
import torch.nn as nn
import torch.optim as optim

# simple model
model = nn.Linear(10, 2)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

mlflow.set_experiment("pytorch-cat-dog")

with mlflow.start_run():
    for epoch in range(5):
        loss = torch.rand(1)  # dummy loss (replace with real training)
        
        # log metrics
        mlflow.log_metric("loss", loss.item(), step=epoch)

    # log params
    mlflow.log_param("learning_rate", 0.001)

    # log model
    mlflow.pytorch.log_model(model, "model")

2026/04/14 14:53:24 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/04/14 14:53:24 INFO mlflow.store.db.utils: Updating database tables
2026/04/14 14:53:25 INFO mlflow.tracking.fluent: Experiment with name 'pytorch-cat-dog' does not exist. Creating a new experiment.
2026/04/14 14:53:26 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/14 14:53:26 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.


In [2]:
import torch

In [3]:
torch.__version__

'2.11.0+cpu'

In [4]:
import numpy as np

In [5]:
lst = [3,4,5,6]
arr = np.array(lst)
print(arr)

[3 4 5 6]


In [6]:
arr.dtype

dtype('int64')

Convert Numpy to Pytorch Tesnors

In [7]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [8]:
tensors

tensor([3, 4, 5, 6])

In [10]:
tensors[1:4]

tensor([4, 5, 6])

In [13]:
tensors[2] =100
tensors

tensor([  3,   4, 100,   6])